In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
#1.Download a sample CSV file of IPL cricket match scores from Kaggle or any public dataset, and use pd.read_csv() to load it into a DataFrame. Print the first 5 rows to verify the data.

In [3]:
pd.read_csv("IPL.csv")

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = pd.read_csv("IPL.csv")

In [5]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# 2.Find a small JSON dataset of trending songs (for example, from Spotify's API samples or any open JSON file), and use pd.read_json() to import it into a DataFrame. Display the DataFrame's column names and data types using df.info().

In [8]:
pd.read_json("spotify_tracks.json")

                                              tracks
0  {'album': {'album_type': 'album', 'artists': [...
1  {'album': {'album_type': 'album', 'artists': [...
2  {'album': {'album_type': 'album', 'artists': [...

In [9]:
df = pd.read_json("spotify_tracks.json")

In [10]:
df

                                              tracks
0  {'album': {'album_type': 'album', 'artists': [...
1  {'album': {'album_type': 'album', 'artists': [...
2  {'album': {'album_type': 'album', 'artists': [...

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tracks  3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [12]:
# 3.You have a TSV (tab-separated values) file containing Zomato restaurant data. Use pd.read_csv() with the correct separator to load the data, and then use df.describe(include='all') to generate summary statistics.<br><br><em><strong>Hint:</strong> The separator for TSV files is '\t'.</em>

In [13]:
 pd.read_csv("zomato_restaurants.tsv", sep="\t")

        restaurant       city  rating  votes
0          Dominos   Vadodara     4.3   1200
1        Pizza Hut     Mumbai     4.1    980
2        McDonalds      Delhi     4.0   1500
3           Subway       Pune     3.9    760
4  Cafe Coffee Day  Ahmedabad     4.2    890
5  Barbeque Nation  Bangalore     4.5   2100

In [14]:
df =  pd.read_csv("zomato_restaurants.tsv")

In [15]:
df

         restaurant\tcity\trating\tvotes
0           Dominos\tVadodara\t4.3\t1200
1            Pizza Hut\tMumbai\t4.1\t980
2            McDonalds\tDelhi\t4.0\t1500
3                 Subway\tPune\t3.9\t760
4   Cafe Coffee Day\tAhmedabad\t4.2\t890
5  Barbeque Nation\tBangalore\t4.5\t2100

In [16]:
df.describe(include="all")

       restaurant\tcity\trating\tvotes
count                                6
unique                               6
top       Dominos\tVadodara\t4.3\t1200
freq                                 1

In [17]:
# 4.Download a large Excel file (at least 10,000 rows) of Flipkart product listings. Use pd.read_excel() with the chunksize parameter to read the file in chunks of 2000 rows, and print the number of rows in each chunk as you iterate.

In [18]:
pd.read_excel("flipkart_products_20000.xlsx")

                 product_name     category  price  rating
0          Flipkart Product 1  Electronics    499     3.5
1          Flipkart Product 2     Clothing    500     3.6
2          Flipkart Product 3         Home    501     3.7
3          Flipkart Product 4        Books    502     3.8
4          Flipkart Product 5  Electronics    503     3.9
...                       ...          ...    ...     ...
19995  Flipkart Product 19996        Books   5494     4.6
19996  Flipkart Product 19997  Electronics   5495     4.7
19997  Flipkart Product 19998     Clothing   5496     4.8
19998  Flipkart Product 19999         Home   5497     4.9
19999  Flipkart Product 20000        Books   5498     5.0

[20000 rows x 4 columns]

In [19]:
df = pd.read_excel("flipkart_products_20000.xlsx")

In [20]:
df.iloc[0:2000]

               product_name     category  price  rating
0        Flipkart Product 1  Electronics    499     3.5
1        Flipkart Product 2     Clothing    500     3.6
2        Flipkart Product 3         Home    501     3.7
3        Flipkart Product 4        Books    502     3.8
4        Flipkart Product 5  Electronics    503     3.9
...                     ...          ...    ...     ...
1995  Flipkart Product 1996        Books   2494     4.6
1996  Flipkart Product 1997  Electronics   2495     4.7
1997  Flipkart Product 1998     Clothing   2496     4.8
1998  Flipkart Product 1999         Home   2497     4.9
1999  Flipkart Product 2000        Books   2498     5.0

[2000 rows x 4 columns]

In [21]:
chunk1 = df.iloc[0:2000]

In [22]:
chunk2 = df.iloc[2000:4000]

In [23]:
chunk3 = df.iloc[4000:6000]

In [37]:
chunk4 = df.iloc[6000:8000]

In [38]:
chunk5 = df.iloc[8000:10000]

In [39]:
chunk6 = df.iloc[10000:12000]

In [40]:
chunk7 = df.iloc[12000:14000]

In [41]:
chunk8 = df.iloc[14000:16000]

In [42]:
chunk9 = df.iloc[16000:18000]

In [43]:
chunk10 = df.iloc[18000:20000]

In [44]:
chunk1

               product_name     category  price  rating
0        Flipkart Product 1  Electronics    499     3.5
1        Flipkart Product 2     Clothing    500     3.6
2        Flipkart Product 3         Home    501     3.7
3        Flipkart Product 4        Books    502     3.8
4        Flipkart Product 5  Electronics    503     3.9
...                     ...          ...    ...     ...
1995  Flipkart Product 1996        Books   2494     4.6
1996  Flipkart Product 1997  Electronics   2495     4.7
1997  Flipkart Product 1998     Clothing   2496     4.8
1998  Flipkart Product 1999         Home   2497     4.9
1999  Flipkart Product 2000        Books   2498     5.0

[2000 rows x 4 columns]

In [45]:
chunk2

               product_name     category  price  rating
2000  Flipkart Product 2001  Electronics   2499     3.5
2001  Flipkart Product 2002     Clothing   2500     3.6
2002  Flipkart Product 2003         Home   2501     3.7
2003  Flipkart Product 2004        Books   2502     3.8
2004  Flipkart Product 2005  Electronics   2503     3.9
...                     ...          ...    ...     ...
3995  Flipkart Product 3996        Books   4494     4.6
3996  Flipkart Product 3997  Electronics   4495     4.7
3997  Flipkart Product 3998     Clothing   4496     4.8
3998  Flipkart Product 3999         Home   4497     4.9
3999  Flipkart Product 4000        Books   4498     5.0

[2000 rows x 4 columns]

In [46]:
chunk3

                product_name     category  price  rating
8000   Flipkart Product 8001  Electronics   3499     3.5
8001   Flipkart Product 8002     Clothing   3500     3.6
8002   Flipkart Product 8003         Home   3501     3.7
8003   Flipkart Product 8004        Books   3502     3.8
8004   Flipkart Product 8005  Electronics   3503     3.9
...                      ...          ...    ...     ...
9995   Flipkart Product 9996        Books   5494     4.6
9996   Flipkart Product 9997  Electronics   5495     4.7
9997   Flipkart Product 9998     Clothing   5496     4.8
9998   Flipkart Product 9999         Home   5497     4.9
9999  Flipkart Product 10000        Books   5498     5.0

[2000 rows x 4 columns]

In [47]:
chunk4

               product_name     category  price  rating
6000  Flipkart Product 6001  Electronics   1499     3.5
6001  Flipkart Product 6002     Clothing   1500     3.6
6002  Flipkart Product 6003         Home   1501     3.7
6003  Flipkart Product 6004        Books   1502     3.8
6004  Flipkart Product 6005  Electronics   1503     3.9
...                     ...          ...    ...     ...
7995  Flipkart Product 7996        Books   3494     4.6
7996  Flipkart Product 7997  Electronics   3495     4.7
7997  Flipkart Product 7998     Clothing   3496     4.8
7998  Flipkart Product 7999         Home   3497     4.9
7999  Flipkart Product 8000        Books   3498     5.0

[2000 rows x 4 columns]

In [48]:
chunk5

                product_name     category  price  rating
8000   Flipkart Product 8001  Electronics   3499     3.5
8001   Flipkart Product 8002     Clothing   3500     3.6
8002   Flipkart Product 8003         Home   3501     3.7
8003   Flipkart Product 8004        Books   3502     3.8
8004   Flipkart Product 8005  Electronics   3503     3.9
...                      ...          ...    ...     ...
9995   Flipkart Product 9996        Books   5494     4.6
9996   Flipkart Product 9997  Electronics   5495     4.7
9997   Flipkart Product 9998     Clothing   5496     4.8
9998   Flipkart Product 9999         Home   5497     4.9
9999  Flipkart Product 10000        Books   5498     5.0

[2000 rows x 4 columns]

In [49]:
chunk6

                 product_name     category  price  rating
10000  Flipkart Product 10001  Electronics    499     3.5
10001  Flipkart Product 10002     Clothing    500     3.6
10002  Flipkart Product 10003         Home    501     3.7
10003  Flipkart Product 10004        Books    502     3.8
10004  Flipkart Product 10005  Electronics    503     3.9
...                       ...          ...    ...     ...
11995  Flipkart Product 11996        Books   2494     4.6
11996  Flipkart Product 11997  Electronics   2495     4.7
11997  Flipkart Product 11998     Clothing   2496     4.8
11998  Flipkart Product 11999         Home   2497     4.9
11999  Flipkart Product 12000        Books   2498     5.0

[2000 rows x 4 columns]

In [50]:
chunk7

                 product_name     category  price  rating
12000  Flipkart Product 12001  Electronics   2499     3.5
12001  Flipkart Product 12002     Clothing   2500     3.6
12002  Flipkart Product 12003         Home   2501     3.7
12003  Flipkart Product 12004        Books   2502     3.8
12004  Flipkart Product 12005  Electronics   2503     3.9
...                       ...          ...    ...     ...
13995  Flipkart Product 13996        Books   4494     4.6
13996  Flipkart Product 13997  Electronics   4495     4.7
13997  Flipkart Product 13998     Clothing   4496     4.8
13998  Flipkart Product 13999         Home   4497     4.9
13999  Flipkart Product 14000        Books   4498     5.0

[2000 rows x 4 columns]

In [51]:
chunk8

                 product_name     category  price  rating
14000  Flipkart Product 14001  Electronics   4499     3.5
14001  Flipkart Product 14002     Clothing   4500     3.6
14002  Flipkart Product 14003         Home   4501     3.7
14003  Flipkart Product 14004        Books   4502     3.8
14004  Flipkart Product 14005  Electronics   4503     3.9
...                       ...          ...    ...     ...
15995  Flipkart Product 15996        Books   1494     4.6
15996  Flipkart Product 15997  Electronics   1495     4.7
15997  Flipkart Product 15998     Clothing   1496     4.8
15998  Flipkart Product 15999         Home   1497     4.9
15999  Flipkart Product 16000        Books   1498     5.0

[2000 rows x 4 columns]

In [52]:
chunk9

                 product_name     category  price  rating
16000  Flipkart Product 16001  Electronics   1499     3.5
16001  Flipkart Product 16002     Clothing   1500     3.6
16002  Flipkart Product 16003         Home   1501     3.7
16003  Flipkart Product 16004        Books   1502     3.8
16004  Flipkart Product 16005  Electronics   1503     3.9
...                       ...          ...    ...     ...
17995  Flipkart Product 17996        Books   3494     4.6
17996  Flipkart Product 17997  Electronics   3495     4.7
17997  Flipkart Product 17998     Clothing   3496     4.8
17998  Flipkart Product 17999         Home   3497     4.9
17999  Flipkart Product 18000        Books   3498     5.0

[2000 rows x 4 columns]

In [53]:
chunk10

                 product_name     category  price  rating
18000  Flipkart Product 18001  Electronics   3499     3.5
18001  Flipkart Product 18002     Clothing   3500     3.6
18002  Flipkart Product 18003         Home   3501     3.7
18003  Flipkart Product 18004        Books   3502     3.8
18004  Flipkart Product 18005  Electronics   3503     3.9
...                       ...          ...    ...     ...
19995  Flipkart Product 19996        Books   5494     4.6
19996  Flipkart Product 19997  Electronics   5495     4.7
19997  Flipkart Product 19998     Clothing   5496     4.8
19998  Flipkart Product 19999         Home   5497     4.9
19999  Flipkart Product 20000        Books   5498     5.0

[2000 rows x 4 columns]

In [54]:
pd.read_csv("paytm_transactions.csv")

  transaction_id;customer;amount;status
0                 101;Bhumi;500;Success
1                     102;Anita;;Failed
2                 103;Rahul;750;Success
3                     104;;1200;Success
4                     105;Priya;;Failed

In [55]:
df = pd.read_csv("paytm_transactions.csv")

In [56]:
df

  transaction_id;customer;amount;status
0                 101;Bhumi;500;Success
1                     102;Anita;;Failed
2                 103;Rahul;750;Success
3                     104;;1200;Success
4                     105;Priya;;Failed

In [57]:
df.isnull().sum()

transaction_id;customer;amount;status    0
dtype: int64